version: "3.9"

services:
  wordpress:
    image: wordpress:6.5-php8.2-apache
    container_name: wp_blog
    ports:
      - "8080:80"
    volumes:
      # WP core tá»« image
      - wp_core:/var/www/html

      # Custom code (mount override)
      - ../public/wp/wp-content:/var/www/html/wp-content

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: wp_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_core:
  db_data: